version: '3'

services:
  db:
    image: 'postgres'
    container_name: questionForm_db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    container_name: questionForm_frontend
    restart: unless-stopped
    build: frontend/
    ports:
      - 80
    depends_on:
      - backend
    command: 'yarn serve'

  backend:
    container_name: questionForm_backend
    restart: unless-stopped
    build: backend/
    env_file: .env
    ports:
      - $BACKEND_PORT
    depends_on:
      - db

volumes:
  db_data:
